Repository Team-KeepGoing/keep-server, pull requests merged in 2024-07, with the labels that each got.

#63 Fix :: change to https redirect
  src/main/java/com/keepgoing/keepserver/global/config/WebSecurityConfig.java
Labels: bug, Fix

#64 Refactor :: code refactor
  src/main/java/com/keepgoing/keepserver/domain/book/payload/request/BookDto.java
  src/main/java/com/keepgoing/keepserver/domain/book/payload/request/BookRequestDto.java
  src/main/java/com/keepgoing/keepserver/domain/book/repository/BookRepository.java
  src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceServiceImpl.java
  src/main/java/com/keepgoing/keepserver/domain/rent/presentation/RentController.java
  src/main/java/com/keepgoing/keepserver/domain/returns/presentation/ReturnController.java
  src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java
  src/main/java/com/keepgoing/keepserver/global/config/SpringConfig.java
  src/main/java/com/keepgoing/keepserver/global/exception/book/BookException.java
Labels: Refactor

#65 Fix :: fix ci-cd build error
  src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java
  src/main/java/com/keepgoing/keepserver/domain/book/payload/request/BookDto.java
  src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java
Labels: bug, Fix, Deploy

#66 Refactor :: refactor user domain related service logics
  src/main/java/com/keepgoing/keepserver/domain/user/controller/UserController.java
  src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserService.java
  src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
Labels: Refactor

#67 Fix :: remove https redirect code
  src/main/java/com/keepgoing/keepserver/global/config/WebSecurityConfig.java
Labels: bug

#69 Feat :: Mapping Image By StudentId
  src/main/java/com/keepgoing/keepserver/domain/student/controller/StudentController.java
  src/main/java/com/keepgoing/keepserver/domain/student/service/StudentService.java
  src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java
Labels: Feat

#70 Fix :: StudentRequestDto
  src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentRequestDto.java
  src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java
Labels: Fix

#72 Fix :: change updatable true
  src/main/java/com/keepgoing/keepserver/domain/book/entity/Book.java
Labels: bug, Fix
