Repository Team-KeepGoing/keep-server, pull requests merged in 2024-06, with the labels that each got.

#37 Fix :: fix user device rental information list & rent logic
  src/main/java/com/keepgoing/keepserver/domain/device/entity/Device.java
  src/main/java/com/keepgoing/keepserver/domain/device/repository/DeviceRepository.java
  src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceServiceImpl.java
Labels: Refactor, Fix

#38 Refactor :: add rental info to /userinfo return value [1/2]
  src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceServiceImpl.java
  src/main/java/com/keepgoing/keepserver/domain/user/controller/UserController.java
  src/main/java/com/keepgoing/keepserver/domain/user/payload/request/UserProfileDto.java
  src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserService.java
  src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
Labels: Feat, Refactor

#40 Refactor :: add rental info to /userinfo return value [2/2]
  src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java
  src/main/java/com/keepgoing/keepserver/domain/book/repository/BookRepository.java
  src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java
  src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java
  src/main/java/com/keepgoing/keepserver/domain/user/controller/UserController.java
  src/main/java/com/keepgoing/keepserver/domain/user/payload/request/UserProfileDto.java
  src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
Labels: Feat, Refactor

#41 Fix :: resolve CORS error
  src/main/java/com/keepgoing/keepserver/domain/user/security/WebSecurityConfig.java
Labels: Fix

#45 Fix :: fix jwt response return value
  src/main/java/com/keepgoing/keepserver/domain/user/payload/response/JwtResponse.java
  src/main/java/com/keepgoing/keepserver/domain/user/security/service/UserDetailsImpl.java
  src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
Labels: Fix

#46 Refactor :: refactor upload logic
  src/main/java/com/keepgoing/keepserver/domain/device/entity/Device.java
  src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java
  src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceDto.java
  src/main/java/com/keepgoing/keepserver/domain/image/dto/ImageDTO.java
  src/main/java/com/keepgoing/keepserver/domain/image/service/ImageService.java
Labels: Fix

#44 Fix :: find student error v2
  src/main/java/com/keepgoing/keepserver/domain/book/presentation/BookController.java
  src/main/java/com/keepgoing/keepserver/domain/book/service/BookService.java
  src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java
  src/main/java/com/keepgoing/keepserver/domain/student/consts/StudentFindType.java
  src/main/java/com/keepgoing/keepserver/domain/student/controller/StudentController.java
  src/main/java/com/keepgoing/keepserver/domain/student/entity/Student.java
  src/main/java/com/keepgoing/keepserver/domain/student/repository/StudentRepository.java
  src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentDto.java
  src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentFindDto.java
  src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentIdDto.java
  src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentRequestDto.java
  src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentResponseDto.java
  src/main/java/com/keepgoing/keepserver/domain/student/service/StudentService.java
  src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java
  src/main/java/com/keepgoing/keepserver/global/exception/book/BookError.java
  src/main/java/com/keepgoing/keepserver/global/exception/book/BookException.java
  src/test/java/com/keepgoing/keepserver/KeepServerApplicationTests.java
Labels: Fix

#49 Refactor :: refactor rental return value
  src/main/java/com/keepgoing/keepserver/domain/book/entity/Book.java
  src/main/java/com/keepgoing/keepserver/domain/book/entity/dto/BookResponseDto.java
  src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java
  src/main/java/com/keepgoing/keepserver/domain/device/entity/Device.java
  src/main/java/com/keepgoing/keepserver/domain/device/enums/DeviceStatus.java
  src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java
  src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceDto.java
  src/main/java/com/keepgoing/keepserver/domain/device/payload/response/DeviceResponseDto.java
  src/main/java/com/keepgoing/keepserver/domain/rent/service/RentServiceImpl.java
Labels: Refactor

#50 Fix :: s3 ACL error
  src/main/java/com/keepgoing/keepserver/global/common/S3/S3Uploader.java
Labels: Fix

#51 Fix :: fix book register return value
  src/main/java/com/keepgoing/keepserver/domain/book/entity/Book.java
  src/main/java/com/keepgoing/keepserver/domain/book/entity/dto/BookDto.java
  src/main/java/com/keepgoing/keepserver/domain/book/entity/dto/BookResponseDto.java
  src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java
  src/main/java/com/keepgoing/keepserver/domain/book/presentation/BookController.java
  src/main/java/com/keepgoing/keepserver/domain/book/service/BookService.java
  src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java
Labels: Refactor, Fix

#52 Refactor :: refactor device request value
  src/main/java/com/keepgoing/keepserver/domain/device/entity/Device.java
  src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java
  src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceDto.java
  src/main/java/com/keepgoing/keepserver/domain/device/payload/response/DeviceResponseDto.java
  src/main/java/com/keepgoing/keepserver/domain/device/payload/response/MyDevicesDto.java
Labels: Refactor

#53 Fix :: fix findAll() return value
  src/main/java/com/keepgoing/keepserver/domain/book/entity/Book.java
  src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java
Labels: Fix

#54 Fix :: fix base response typo
  src/main/java/com/keepgoing/keepserver/global/common/BaseResponse.java
Labels: bug, Fix

#55 Feat :: create device edit api
  src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceEditRequest.java
  src/main/java/com/keepgoing/keepserver/domain/device/presentation/DeviceController.java
  src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceService.java
  src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceServiceImpl.java
Labels: Feat

#56 Fix :: edit student service
  src/main/java/com/keepgoing/keepserver/domain/student/controller/StudentController.java
  src/main/java/com/keepgoing/keepserver/domain/student/repository/StudentRepository.java
  src/main/java/com/keepgoing/keepserver/domain/student/service/StudentService.java
  src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java
Labels: Fix

#57 Fix :: fix typo + swagger desc
  src/main/java/com/keepgoing/keepserver/domain/device/presentation/DeviceController.java
  src/main/java/com/keepgoing/keepserver/domain/user/payload/request/UserProfileDto.java
Labels: Fix

#61 Refactor :: remove static
  src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java
  src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java
Labels: Refactor, Fix
